name: gh_pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: setup_git
      run: git config --global url."https://x-access-token:${{ secrets.ACTIONS_PAC }}@github.com/".insteadOf "git@github.com:"

    - uses: actions/checkout@v1
      with:
        submodules: recursive
        token: ${{ secrets.ACTIONS_PAC }}

    - name: setup_node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: cache_dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: cache_extensions
      uses: actions/cache@v1
      with:
        path: extensions
        key: ${{ runner.os }}-extensions-${{ hashFiles('gatsby-config.js') }}
        restore-keys: |
          ${{ runner.os }}-extensions-

    - run: npm install

    - run: npm run test

    - run: npx gatsby telemetry --disable

    - run: npm run build

    - name: deploy
      run: npx now --token ${{ secrets.ZEIT_TOKEN }}
